#!/bin/sh

set -e

if [ -z "$RTE_SDK" ]; then
    echo "RTE_SDK - Points to the DPDK installation directory."
    exit 1
fi

if [ -z "$RTE_TARGET" ]; then
    RTE_TARGET=`uname -m`"-native-"`uname -s | tr '[:upper:]' '[:lower:]'`"app-gcc"
fi

bindgen -builtins src/rte.h -o src/raw.rs -I $RTE_SDK/$RTE_TARGET/include

PATCH=`cat <<EOM
--- a/rte-sys/src/raw.rs
+++ b/rte-sys/src/raw.rs
@@ -1,3 +1,8 @@
+#![allow(dead_code)]
+#![allow(non_camel_case_types)]
+#![allow(non_snake_case)]
+#![allow(non_upper_case_globals)]
+
 /* automatically generated by rust-bindgen */

 pub type __int128_t = ::std::os::raw::c_void;
@@ -1569,6 +1574,7 @@ impl ::std::default::Default for Struct_cons {
 pub struct Struct_rte_mempool_cache {
     pub len: ::std::os::raw::c_uint,
     pub objs: [*mut ::std::os::raw::c_void; 1536usize],
+    pad: [u8; 56],
 }
 impl ::std::clone::Clone for Struct_rte_mempool_cache {
     fn clone(&self) -> Self { *self }
@@ -1625,6 +1631,7 @@ pub struct Struct_rte_mempool {
     pub header_size: uint32_t,
     pub trailer_size: uint32_t,
     pub private_data_size: ::std::os::raw::c_uint,
+    pad: [u8; 48],
     pub local_cache: [Struct_rte_mempool_cache; 128usize],
     pub pg_num: uint32_t,
     pub pg_shift: uint32_t,
EOM
`

echo "$PATCH" | git apply -
